url: https://vikitheolorado.github.io
baseurl: /

# Site settings
title: Viki Theolorado
email: vikitheolorado@gmail.com
description: "I'm a skilled Full-Stack Developer specializing in building scalable web applications with ReactJS and .NET Core. I’m passionate about delivering high-quality, innovative solutions that optimize business operations."

# Team names, titles and social links
people:
  - name: Viki Theolorado
    pic: 1
    position: Full-Stack Developer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/8531761/viki-theolorado
  - title: github
    url: http://github.com/vikitheolorado

# Postal address (add as many lines as necessary)
address:
  - line: Villa Serpong
  - line: Tangerang Selatan, Indonesia

# Build settings
markdown: kramdown
permalink: pretty
